/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
**                   Auther: Qiang Xin Bo                          **
********************************************************************/

#ifndef __DMQUEUE_H_INCLUDE__
#define __DMQUEUE_H_INCLUDE__

#include <stddef.h>

class CDMQueue
{
public:
    CDMQueue(void)
        : m_pArray(NULL), m_nHead(0), m_nTail(0), m_nSize(0)
    {

    }

    ~CDMQueue(void)
    {
        delete []m_pArray;
        m_nHead = 0;
        m_nTail = 0;
        m_nSize = 0;
    }

    bool Init(int nSize)
    {
        m_nSize = nSize+1;
        m_pArray = new void*[m_nSize]();
        return true;
    }

    bool PushBack(void* ptr)
    {
        int nDist = m_nTail + m_nSize - m_nHead;
        int nUsed = nDist >= m_nSize ? (nDist-m_nSize) : nDist;

        if(nUsed >= m_nSize-1)
            return false;

        m_pArray[m_nTail] = ptr;
        if(++m_nTail >= m_nSize)
            m_nTail = 0;

        return true;
    }

    void * PopFront()
    {
        int nDist = m_nTail + m_nSize - m_nHead;
        int nUsed = nDist >= m_nSize ? (nDist-m_nSize) : nDist;
        if(0 == nUsed)
            return NULL;

        void* ptr = m_pArray[m_nHead];
        if(++m_nHead >= m_nSize)
            m_nHead = 0;

        return ptr;
    }


protected:
    void**  m_pArray;
    int   m_nHead;
    int   m_nTail;
    int   m_nSize;
};

#endif // __DMQUEUE_H_INCLUDE__
