/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
**                   Auther: Qiang Xin Bo                          **
********************************************************************/
#ifndef __DMTIMERSINK_H_INCLUDE__
#define __DMTIMERSINK_H_INCLUDE__

#include "dmos.h"
#include "list.h"
#include "dmany.hpp"

#define TVN_BITS 6
#define TVR_BITS 8
#define TVN_SIZE (1 << TVN_BITS)
#define TVR_SIZE (1 << TVR_BITS)
#define TVN_MASK (TVN_SIZE - 1)
#define TVR_MASK (TVR_SIZE - 1)

#define TIME_NOT_EQ(x, y) ((x) != (y))
#define INDEX(t, N) ((t >> (TVR_BITS + (N) * TVN_BITS)) & TVN_MASK)

typedef struct tvec
{
    struct list_head vec[TVN_SIZE];
}TVec;

typedef struct tvec_root
{
    struct list_head vec[TVR_SIZE];
}TVec_Root;

class ITimerSink
{
public:
    virtual ~ITimerSink() = 0;
    virtual void OnTimer(unsigned long long qwIDEvent) = 0;
    virtual void OnTimer(unsigned long long qwIDEvent, dm::any& oAny){ OnTimer(qwIDEvent); }
};

inline ITimerSink::~ITimerSink()
{

}

class CDMTimerElement
{
public:
    CDMTimerElement(){ Reset(); }
    ~CDMTimerElement(){ Reset(); }

    inline void Reset()
    {
        m_stEntry.next = NULL;
        m_stEntry.prev = NULL;

        m_qwNextTime = 0;
        m_qwElapse = 0;
        m_qwID = 0;

        m_poTimerSink = NULL;

        m_bErased = false;
        m_bExact = false;
    }

    inline void Kill(){ m_bErased = true; }

public:
    struct list_head    m_stEntry;

    unsigned long long  m_qwNextTime;
    unsigned long long  m_qwElapse;
    unsigned long long  m_qwID;

    ITimerSink*         m_poTimerSink;

    bool                m_bErased;
    bool                m_bExact;
    dm::any             m_oAny;
};

#endif // __DMTIMERSINK_H_INCLUDE__

