/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
**                   Auther: Qiang Xin Bo                          **
********************************************************************/
#ifndef __DMTYPES_H_INCLUDE__
#define __DMTYPES_H_INCLUDE__

#ifdef _MSC_VER
#include "msinttypes/stdint.h"
#include "msinttypes/inttypes.h"
#else
// Other compilers should have this.
#include <stdint.h>
#include <inttypes.h>
#include <sys/time.h>

#endif

#endif // __DMTYPES_H_INCLUDE__
