name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: relwithdebinfo

jobs:
  unix:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: lukka/get-cmake@latest

      - name: Create Build Environment
        # Some projects don't allow in-source building, so create a separate build directory
        # We'll use this as our working directory for all subsequent commands
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: build
        # working-directory: ${{runner.workspace}}
        shell: bash
        run: |
          cmake --version
          cmake -B build -DCMAKE_BUILD_TYPE=$BUILD_TYPE
          cmake --build build --config $BUILD_TYPE

      - name: Test
        # working-directory: ${{runner.workspace}}
        shell: bash
        # Execute tests defined by the CMake configuration.  
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest -C $BUILD_TYPE
  win:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
        arch:
          - amd64
          - amd64_x86
          - amd64_arm64
    steps:
      - uses: actions/checkout@v2
      - uses: lukka/get-cmake@latest
      # - uses: seanmiddleditch/gha-setup-vsdevenv@master
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - name: Create Build Environment
        # Some projects don't allow in-source building, so create a separate build directory
        # We'll use this as our working directory for all subsequent commands
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: build
        # working-directory: ${{runner.workspace}}
        shell: cmd
        run: |
          cmake --version
          cmake -B build -DCMAKE_BUILD_TYPE=$BUILD_TYPE
          cmake --build build --config $BUILD_TYPE

      - name: Test
        # working-directory: ${{runner.workspace}}
        shell: cmd
        # Execute tests defined by the CMake configuration.  
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest -C $BUILD_TYPE
