name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: relwithdebinfo

jobs:
  boost_ext_ut:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: lukka/get-cmake@latest

      - name: Create Build Environment
        # Some projects don't allow in-source building, so create a separate build directory
        # We'll use this as our working directory for all subsequent commands
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: build
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake -A x64 -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
          cmake --build . --config $BUILD_TYPE
